spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 数据存储配置
data:
  storage:
    # 存储类型: influxdb, redis
    type: influxdb
    enabled: true
    retention-time: 86400  # 24小时（秒）
    batch-size: 100
    write-interval: 5000   # 5秒（毫秒）
    
    # InfluxDB配置
    influx:
      url: http://127.0.0.1:8086
      token: x
      org: ems
      bucket: ems_data
      table: ems_data
      connection-timeout: 10000
      read-timeout: 30000
      write-timeout: 10000
    # Redis配置  
    redis:
      key-prefix: "protocol:"
      database: 0
      time-to-live: 86400  # 24小时（秒）
      use-key-expiration: true
      serialization: json
# RocketMQ配置
rocketmq:
  # ===========================================
  # RocketMQ消息队列总开关
  # true: 启用RocketMQ消息推送功能
  # false: 禁用RocketMQ消息推送功能
  # ===========================================
  enabled: false  # 设置为true已启用，设置为false可禁用  
  # Name Server地址（多个地址用分号分隔）
  name-server: 127.0.0.1:19876  
  # 报警主题名称
  alarm-topic: alarm-topic
  # 生产者配置
  producer:
    group: alarm-producer-group
    send-message-timeout: 3000            # 发送消息超时时间(ms)
    retry-times-when-send-failed: 2        # 同步发送失败重试次数
    retry-times-when-send-async-failed: 2  # 异步发送失败重试次数
    max-message-size: 4096                 # 消息最大大小(bytes)
    compress-message-body-threshold: 4096  # 消息压缩阈值(bytes)
  # 消费者配置
  consumer:
    group: alarm-consumer-group
    consume-message-batch-max-size: 1  # 批量消费最大消息数
    consume-timeout: 15                # 消费超时时间(分钟)
mqtt:
  # MQTT客户端配置（用于连接外部MQTT服务器）
  client:
    enabled: true
    broker-url: tcp://127.0.0.1:1884
    client-id: protocol-server-client
    username: 
    password: 
    keep-alive: 60
    clean-session: true
    auto-reconnect: true
    reconnect-delay: 5000  # 重连延迟（毫秒）
    max-reconnect-delay: 60000  # 最大重连延迟（毫秒）